version: "3"


services:
   app:
      build:
        context: .
      ports:
      - "8000:8000"
      volumes:
      - .:/app
      restart: always
      environment:
        - SECRET_KEY="developmentsecretkey"
        - DB_HOST=db
        - DB_NAME=cashflow_db
        - DB_USER=root
        - DB_PASS=mongoadmin
      command: >
        sh -c "
            python manage.py migrate  &&
            python manage.py runserver 0.0.0.0:8000"
      depends_on:
        - db

   db:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_DATABASE: cashflow_db


